version: "3.3"
services:
  simulator:
    command: ["python", "-m", "tr_ap_xps.simulator.h5_simulator",  "/sample_data/trs_small.h5",  "00014", "--log-level", "INFO"]
    build:
      context: .
      dockerfile: Dockerfile_labviewsim
    volumes:
      - ./sample_data:/sample_data
    networks:
      aps_net:
networks:
  aps_net:
    driver: bridge
