FROM python:3.13

WORKDIR /app

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

# Copy dependency files first for better caching
COPY pyproject.toml /app/

# Copy the rest of the application
COPY . /app

# Install dependencies
RUN uv pip install --system --no-cache .



ENTRYPOINT ["arroyo", "run"]
