
version: "3.3"
services:
  tiled:
    # see the file ./tiled/deploy/config.yml for detailed configuration of tiled
    image: ghcr.io/bluesky/tiled:v0.1.0a122
    ports:
      - "8000:8000"
    environment:
      - TILED_SINGLE_USER_API_KEY=${TILED_SINGLE_USER_API_KEY}
    volumes:
      - ./services/tiled/deploy:/deploy:Z
      - ./data:/data:Z
    restart: unless-stopped
    networks:
      aps_net:

  processor:
    # command: python -m tr_ap_xps.processor.cli --zmq-pub-address tcp://simulator
    build:
      context: .
      dockerfile: Dockerfile_processor
    restart: unless-stopped
    volumes:
      - .:/app:Z
    networks:
      aps_net:

  wspublisher:
    build:
      context: .
      dockerfile: Dockerfile_wspublisher
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - .:/app:Z
    networks:
      aps_net:


networks:
  aps_net:
    driver: bridge
