FROM python:3.11

WORKDIR /app

RUN apt install git


COPY . /app
RUN pip install ./arroyo
RUN pip install --no-cache-dir --upgrade .
RUN pip install --no-cache-dir .[simulator]

CMD ["python", "-m", "tr_ap_xps.simulator.simulator", "--log-level", "INFO"]
