services:
  tiled:
  # see the file ./tiled/deploy/config.yml for detailed configuration of tiled
  image: ghcr.io/bluesky/tiled:main
  ports:
  - "8000:8000"
  environment:
  - TILED_SINGLE_USER_API_KEY=${TILED_SINGLE_USER_API_KEY}
  volumes:
  - ./services/tiled/deploy:/deploy:Z
  - ./data:/data:Z
  restart: unless-stopped
  healthcheck:
  test: ["CMD", "curl", "-f", "http://tiled:8000/healthz"]
  interval: 10s
  timeout: 5s
  retries: 3
  networks:
  aps_net:

  labview_processor:
    build:
      context: .
      dockerfile: Dockerfile_labview_processor
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - .:/app:Z
    networks:
      aps_net:
    depends_on:
      tiled:
        condition: service_healthy

  timepix_processor:
    build:
      context: .
      dockerfile: Dockerfile_timepix_processor
    restart: unless-stopped
    ports:
      - "8002:8001"
    volumes:
      - .:/app:Z
    networks:
      aps_net:
    depends_on:
      tiled:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - .:/app:Z
    networks:
      aps_net:

networks:
  aps_net:
    driver: bridge
