xps_operator:
  log_level: "INFO"
  tiled_uri: "http://localhost:8000"
  lv_zmq_listener:
    zmq_pub_address: "tcp://931-apxps-es23.dhcp.lbl.gov"
    zmq_pub_port: 5657
  websockets_publisher:
    host: "0.0.0.0"
    port: 8001
