xps:
  log_level: "INFO"
  tiled_uri: "http://localhost:8000"
  lv_zmq_listener:
    zmq_pub_address: "tcp://localhost"
    zmq_pub_port: 5555
  websockets_publisher:
    host: "localhost"
    port: 8001
