xps:
  log_level: "INFO"
  tiled_uri: "http://tiled:8000"
  tiled_api_key: "@env TILED_SINGLE_USER_API_KEY"
  lv_zmq_listener:
    zmq_pub_address: "tcp://simulator"
    zmq_pub_port: 5555
  websockets_publisher:
    host: "0.0.0.0"
    port: 8001
